name: Lint

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'

jobs:
  lint:
    uses: chodeus/chodeus-ops/.github/workflows/python-ci.yml@main
    with:
      python_versions: '["3.12"]'
      run_tests: false
      install_command: 'pip install flake8'
      lint_command: >-
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics &&
        flake8 . --count --max-complexity=25 --max-line-length=127 --statistics
