name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: chodeus/chodeus-ops/.github/workflows/release-please.yml@0469c75e0002d118473db2aeff288cf7f5fa70de # main
