name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@143b4da181660d72e7ca4404c7c1e1e1dd5be750 # main
