name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@05f4e436f2400295e71046a85e853b422417b172 # main
